Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/03/2023
Var
// Seção de Declarações das variáveis 
 A,B,C: REAL

 INICIO
// SEÇAO  DE COMANDOS,
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo